drop table if exists category cascade;

create table category (
    id bigint generated by default as identity,
    parent bigint,
    name varchar(50) not null unique,
    primary key (id)
);

alter table if exists category
    add constraint FK_CATEGORY_PARENT_CATEGORY_ID
        foreign key (parent) references category;
